name: cv-project
channels:
  - conda-forge
dependencies:
  - opencv=4.6.0
  - python=3.9
  - numpy=1.23.5
  - black=22.10.0
  - matplotlib=3.6.2
  - pillow=9.3.0
  - scikit-learn=1.2.0
  - pip:
    - rembg==2.0.29
